# This workflow provided by GitHubActions.js project
# Documentation: https://github.com/vemel/github_actions_js
#
# --- How to modify this workflow and still get updates ---
# - Set 'github-actions-managed' to false on manual edit to prevent step overwrite on update
# - User-added steps survive update as well
# - Deleted steps are restored on update, so make them empty instead of removing
# - Do not add multiple jobs, only one job is supported
# - This comment is user-editable and is not updated automatically

name: Run style checks and unit tests
"on":
  push: {}
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout current branch
        id: checkout
        uses: actions/checkout@v2
        with:
          github-actions-managed: true
      - name: Get available scripts
        id: scripts
        uses: actions/github-script@v3
        with:
          github-actions-managed: true
          script: |
            const { promisify } = require('util');
            const exec = promisify(require('child_process').exec);

            // Script to run linting
            const lintScript = 'lint';

            // Script to run unit tests
            const testScript = 'test';

            const output = (await exec('npm run')).stdout;
            const scripts = output.split(/\r?\n/)
              .filter(line => line.startsWith('  ') && !line.startsWith('   '))
              .map(line => line.trim());

            let result = undefined;
            if (scripts.includes(lintScript)) {
              core.setOutput('lint', lintScript);
              result = true;
            }
            if (scripts.includes(testScript)) {
              core.setOutput('test', testScript);
              result = true;
            }
            return result;
      - name: Cache npm downloads
        uses: actions/cache@v2
        id: cache
        if: steps.scripts.outputs.result
        with:
          github-actions-managed: true
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      - name: Set up Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          github-actions-managed: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install package
        id: install
        if: steps.scripts.outputs.result
        run: |
          # github-actions-managed: true
          npm install -g npm
          npm ci
      - name: Run linting
        id: lint
        if: steps.scripts.outputs.lint
        run: |
          # github-actions-managed: true
          echo "Running: npm run ${{ steps.scripts.outputs.lint }}"
          npm run ${{ steps.scripts.outputs.lint }}
      - name: Run tests
        id: test
        if: steps.scripts.outputs.test
        run: |
          # github-actions-managed: true
          echo "Running: npm run ${{ steps.scripts.outputs.test }}"
          npm run ${{ steps.scripts.outputs.test }}
